name: neos_chat
description: "A Flutter Chat SDK."
version: 0.0.1
repository: https://github.com/KareemArafat/Neos-Chat.git
#homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^3.1.2
  http: ^1.2.2
  intl: ^0.20.2
  flutter_sound: ^9.23.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  open_filex: ^4.7.0
  shared_preferences: ^2.3.3
  audioplayers: ^6.4.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
